services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    # image: omega1996/krasivo-bot
    env_file:               
      - .env
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/${MONGO_DB_NAME}?authSource=admin"

    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: telegram-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:               
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2
    container_name: telegram-mongo-express
    env_file:              
      - .env
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    restart: unless-stopped

volumes:
  mongo-data:
